baseurl = "/"
languageCode = "en-au"
title = "Richard de Rozario"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "richardderozario"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$","\\.Rproj", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/RdR1024"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/rderozario"
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/rstudio"

[params]
    description = "Living the analytical life in Melbourne"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "RdRfacetiny2014.jpg"
    width = 55
    height = 64
    alt = "RdR"

